// <auto-generated />
namespace Examination_system.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class problem_desc_req : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(problem_desc_req));
        
        string IMigrationMetadata.Id
        {
            get { return "201907191731186_problem_desc_req"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
